### ISSUE TITLE
PowerBIClient: Reports.GenerateToken throws Forbidden error.

### ISSUE THREAD

**Issue by sm-dgdgeng** [Microsoft/PowerBI-CSharp#108] opened 2017-07-03 16:07 UTC
Hi,
I have a valid access token and able to pull the list of reports, however "GenerateToken" fails with Forbidden error. Below is the code snippet. I have registered an Native Azure application and have assigned all delegated permission to Power BI Service.

thanks in advance for the help.

                // Create a user password cradentials.
                UserPasswordCredential UserCredentials = new UserPasswordCredential(Username, Password);
                // Authenticate using created credentials
                AuthenticationContext AuthContext = new AuthenticationContext("https://login.windows.net/common/oauth2/authorize/", false);
                AuthenticationResult AuthResult = await AuthContext.AcquireTokenAsync("https://analysis.windows.net/powerbi/api", ClientId, UserCredentials);

                TokenCredentials TknCredentials = new TokenCredentials(AuthResult.AccessToken, "Bearer");

                using (PowerBIClient Client = new PowerBIClient(new Uri(ApiUrl), TknCredentials))
                {
                    // Get a list of reports.
                    ODataResponseListReport Reports = Client.Reports.GetReports();

                    // Get the first report in the group.
                    Report PBIReport = Reports.Value.FirstOrDefault();

                    // Generate Embed Token.
                    GenerateTokenRequest generateTokenRequestParameters = new GenerateTokenRequest(accessLevel: "view");
                    EmbedToken tokenResponse = Client.Reports.GenerateToken(PBIReport.Id, generateTokenRequestParameters);
                }

Error: Operation returned an invalid status code 'Forbidden'
Stack Trace:
   at Microsoft.PowerBI.Api.V2.Reports.<GenerateTokenWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.V2.ReportsExtensions.<GenerateTokenAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.V2.ReportsExtensions.GenerateToken(IReports operations, String reportKey, GenerateTokenRequest requestParameters)

**Comment by celfrumos** [comment] 2017-07-03 21:48
I'm having basically the exact same problem, though I'm writing for a Server-Side Web app. 

I've quintuple checked all the data I'm passing in is correct, and I can make api calls with apiary or manual code, I get valid access tokens and can pull the data manually, but none of the calls on the PowerBIClient work at all -- I get the same `Forbidden` error every single time, regardless of the call I'm trying to make on the PowerBIClient. The most frustrating thing is that I'm not even getting any useful error information.

Here's my stack tracke after the call if it'll help:

`[HttpOperationException: Operation returned an invalid status code 'Forbidden']`
>    Microsoft.PowerBI.Api.V2.<GetReportsInGroupWithHttpMessagesAsync>d__12.MoveNext() +2666
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
>    Microsoft.PowerBI.Api.V2.<GetReportsInGroupAsync>d__15.MoveNext() +259
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
>    Microsoft.PowerBI.Api.V2.ReportsExtensions.GetReportsInGroup(IReports operations, String groupId) +45

**Comment by mikeblakeuk** [comment] 2017-07-05 15:22
This is yet **_another_** issue wherer Power BI doesn't return the real error.
a) Currently you need to make sure you are within a Group. "Root" (non group) reports are currently not supported.

b) You can see the real exception using fiddler.
![image](https://user-images.githubusercontent.com/1986660/27871625-17ca1d22-619e-11e7-9a6c-392411195048.png)

c) You can look at the exception body or use my gist to get the real exception
https://gist.github.com/mikeblakeuk/b9062d9b2f68cc3830591009b0e59889

**Comment by ArbelaBrandon** [comment] 2017-07-07 21:21
When you stated that your within a Group, yet when you login and want to get a list of groups with client.Groups.GetGroups() that will not work either? How then can you get a list of groups to work with, and then work within that group? Is there a good example?

**Comment by SebastianGuerreroCardenas** [comment] 2017-07-25 20:46
Will this get support  for non group reports? also is this supported for powerbi embedded?

**Comment by sm-dgdgeng** [comment] 2017-08-17 05:11
Turns out that Workspaces will be listed with "client.Groups.GetGroups()" (however the default workspace "me" is not listed there). Not sure if "Group" and "Workspace" are intechangeable in this context, but I was able to make progress and get my embedded reports working. (Certainly not Intuitive).

**Comment by ali-hamud** [comment] 2017-08-20 14:46
"Group" and "Workspace" are the same.
I will keep this issue open until we fix the error handling in SDK.
SDK should return a specific error message.

**Comment by cassianopeixoto** [comment] 2017-11-09 12:58
I am facing the same situation. The user that I am using have access to the group, however not able to generate the token. I would like to know the reason. Any updates? =)

**Comment by ali-hamud** [comment] 2017-11-09 13:05
What errors do you see in Netwrok capture?
It could be that the registered AAD application didn't request access to user groups.

![image](https://user-images.githubusercontent.com/23071967/32606828-740b0040-c55f-11e7-997e-8a8be1a37764.png)

**Comment by cassianopeixoto** [comment] 2017-11-09 13:53
Hi @ali-hamud , It's all right with the permissions. It's returning "Operation returned an invalid status code 'Forbidden'" when system execute the following line:

var embeddedToken = client.Dashboards.GenerateTokenInGroup(this.GroupId, dashboardID, new GenerateTokenRequest("View"));

The stranger thing that user is able to execute the following line:

var dashboards = client.Dashboards.GetDashboardsInGroup(this.GroupId);

**Comment by ali-hamud** [comment] 2017-11-09 14:53
Do you see the dashboard-Id in the list of dashboards returned from GetDashboardsInGroup?

**Comment by lamnv5490** [comment] 2017-11-09 14:58
Currently, I'm using this sample https://github.com/guyinacube/Embed-API-Sample. And I have the same issues.

1. I changed clientId, username, password then I got:
 `The request body must contain the following parameter: 'client_secret or client_assertion'`
2. After some researched I found that I should use
`var clientCre = new ClientCredential(clientId, clientSecret)`
This case I already got token. But then got stuck again in
`using (var client = new PowerBIClient(new Uri(apiUrl), tokenCredentials))
{ 
var groups = client.Groups.GetGroups();
 } `
It said Microsoft.Rest.HttpOperationException: 'Operation returned an invalid status code 'Forbidden''.

**Comment by cassianopeixoto** [comment] 2017-11-09 15:23
@ali-hamud Yes, it's returning without any problem.

**Comment by cassianopeixoto** [comment] 2017-11-09 15:28
@lamnv5490 For embedded purporse the application should be configured as Native App. The snipped that worked for me was:

            var credential = new UserPasswordCredential(this.Username, this.Password);
            var authenticationContext = new AuthenticationContext("https://login.windows.net/common/oauth2/authorize");
            var authenticationResult = await authenticationContext.AcquireTokenAsync("https://analysis.windows.net/powerbi/api", this.ClientId, credential);
            var tokenCredentials = new TokenCredentials(authenticationResult.AccessToken, authenticationResult.AccessTokenType);

            using (var client = new PowerBIClient(new Uri("https://api.powerbi.com/"), tokenCredentials))
            {
                var dashboards = client.Dashboards.GetDashboardsInGroup(this.GroupId);
            }

**Comment by ali-hamud** [comment] 2017-11-09 15:33
Hi @lamnv5490 
yes, you need a native app.
please take a look here:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-register-app/

**Comment by Xakkep** [comment] 2017-11-20 17:01
There is an additional detail which was not so intuitive. After permissions are changed and saved (in Azure portal), one must hit "Grant Permissions" button, for permissions to actually go into effect. After which a new access token needs to be obtained.
![image](https://user-images.githubusercontent.com/265059/33030857-7471c620-cdea-11e7-8512-a339102549cb.png)

**Comment by lamnv5490** [comment] 2017-11-21 03:45
@ali-hamud Thank you. I have done but there are a little bit difficult with .NET CORE 2.0. Soon, I will upload my code sample.

**Comment by cassianopeixoto** [comment] 2017-11-22 10:50
Somehow, my problem was solved. I guess that was related with account syncronization of AD => Azure => Power BI

**Comment by ali-hamud** [comment] 2017-11-22 12:11
Hi, seems like the problem is solved for everybody.
I will close the issue, please reopen if you have more questions.

**Closed by ali-hamud** 2017-11-22 12:11 UTC
Labels: enhancement

**Comment by BereketTikui** [comment] 2018-01-10 19:51
Hi, 
I am getting same error 'Operation returned an invalid status code 'Forbidden''. Getting all the dashboards for a given groupId is working fine (GetDashboardsInGroupAsync), but I am getting the forbidden error when I run the code below 

var tokenResponse = await client.Dashboards.GenerateTokenInGroupAsync(GroupId, dashboard.Id, generateTokenRequestParameters);

I am not sure what missed. I have configured the permissions in Azure like 

![image](https://user-images.githubusercontent.com/28549768/34792273-776f4e08-f615-11e7-8747-e4c76d82cd99.png)

and 

![image](https://user-images.githubusercontent.com/28549768/34792296-8f5c4174-f615-11e7-9cd4-e2f7e6702c37.png)

Thanks for the help!

**Comment by ali-hamud** [comment] 2018-01-11 08:47
Do you get any errors in response body? or just forbidden?

**Comment by BereketTikui** [comment] 2018-01-12 16:14
It was giving me forbidden, that issue is not there anymore after a re-register the application as Native app. now I am getting error when trying to call 
var tokenResponse = await client.Dashboards.GenerateTokenInGroupAsync(GroupId, dashboard.Id, generateTokenRequestParameters);

![image](https://user-images.githubusercontent.com/28549768/34884111-af4c6b38-f789-11e7-87c0-cd83ec38091f.png)

**Comment by ali-hamud** [comment] 2018-01-14 15:29
please file support ticket for this as we need more details.
